### ISSUE TITLE
Command "interrupts" line Coroutine

### ISSUE THREAD

**Issue by mikeevmm** [thesecretlab/YarnSpinner#68] opened 2017-03-30 11:23 UTC
I ran into some issues, because I wasn't aware that having some text with a command in it would dispatch `RunLine`, `RunCommand`, `RunLine`.

This should probably be mentioned in the docs to avoid confusion :)

**Comment by bowlercaptain** [comment] 2017-04-08 21:15
Tested and reproduced. Calling a line "Hey what's <<move left>> up?" results in Runline("Hey what's "), then when that returns, RunCommand(move left), then RunLine(" up?").

This isn't totally out of line, as the Yarn editor shows inline commands highlighted in purple, even when they aren't on their own line. However, it definitely feels like the yarn specifications implies a single line or command per line. I'll check over to see which yarn dictates, and where YS is doing this. This feels like very clean graceful failure rather than a feature or a bug.

**Comment by desplesda** [comment] 2017-04-09 01:19
This would be happening because the lexer is reading all the raw text it can until it hits any of the delimiter rules (currently, this means the tokens that begin commands, shortcut options, and options.) There's no concept of a token being 'embedded' in another, so it stops and starts on the `<<move left>>` command, and then returns to the text `up?` when done. (See [Lexer.cs](https://github.com/thesecretlab/YarnSpinner/blob/master/YarnSpinner/Lexer.cs#L370) for more info.)

I'm not really sure if there's a better way to do this. If the intent in your example is to start the character moving left after "hey what's" has appeared, I'd probably do something like run the `<<move left>>` command first, but with a delay.

**Comment by desplesda** [comment] 2017-04-09 01:20
I guess we could make the compiler emit a warning or error if you put a command in the same line as text?

**Comment by mikeevmm** [comment] 2017-04-09 19:42
@desplesda For context, the way I was using the command was to style the text, so that

```yarn
Not <<startshake>>him<<endshake>> again!
```

would produce a bolded, shaking "him" :)

**Comment by desplesda** [comment] 2017-04-09 20:40
If it helps, Night in the Woods did this by using a BBCode-style markup:

`This text is [shake=2]shaking[/shake]`

**Comment by mikeevmm** [comment] 2017-04-21 15:16
Is it safe to close this then? Seems like this is expected and it's recommended to use custom tag marking.

**Comment by desplesda** [comment] 2017-04-22 01:46
Yup. Closing this.

**Closed by desplesda** 2017-04-22 01:46 UTC
